/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.moon.view;

import com.mycompany.moon.model.CategoryDAO;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import tools.TimeConvert;

/**
 *
 * @author edithson
 */
public class Category extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Category.class.getName());

    private ArrayList<Integer> tab_id_cat = new ArrayList<>();
    List<Map<String, Object>> list = null;
    private CategoryDAO cat = new CategoryDAO();
    private int cat_id;
    private Home home;
    /**
     * Creates new form Category
     */
    public Category(Home home) {
        initComponents();
        fill_cat_list("");
        this.home = home;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jButton1 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        jMenuItem1.setText("Modifier");
        jMenuItem1.addActionListener(this::jMenuItem1ActionPerformed);
        jPopupMenu1.add(jMenuItem1);

        jMenuItem2.setText("Supprimer");
        jMenuItem2.addActionListener(this::jMenuItem2ActionPerformed);
        jPopupMenu1.add(jMenuItem2);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("moon note - category");
        setAlwaysOnTop(true);
        setResizable(false);

        jButton1.setFont(new java.awt.Font("JetBrains Mono Light", 0, 17)); // NOI18N
        jButton1.setText("Ajouter");
        jButton1.addActionListener(this::jButton1ActionPerformed);

        jTextField1.setFont(new java.awt.Font("JetBrains Mono Light", 0, 17)); // NOI18N
        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField1KeyReleased(evt);
            }
        });

        jTable1.setFont(new java.awt.Font("JetBrains Mono Light", 0, 17)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTable1.setComponentPopupMenu(jPopupMenu1);
        jTable1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jTable1.setRowHeight(30);
        jTable1.setRowSelectionAllowed(false);
        jTable1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);
        jTable1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jTable1.getTableHeader().setResizingAllowed(false);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jTable1MouseReleased(evt);
            }
        });
        jScrollPane2.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // Ajout d'une nouvelle catégorie
        String nom = jTextField1.getText().toString();
        if (nom == null || nom.trim().isEmpty()|| nom == " ") {
            JOptionPane.showMessageDialog(
                this,
                "La catégorie doit avoir un nom valide", // Le message
                "Erreur", // Le titre de la boîte de dialogue
                JOptionPane.ERROR_MESSAGE // Le type de message (icône d'exclamation)
            );
            return;
        }
        cat.insert(nom);
        this.home.refresh_cat();
        jTextField1.setText("");
        fill_cat_list("");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTable1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseReleased
        int index = jTable1.getSelectedRow();
        DefaultTableModel model = (DefaultTableModel)jTable1.getModel();
        cat_id = tab_id_cat.get(index);
    }//GEN-LAST:event_jTable1MouseReleased

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // suppression d'une note
        int index = jTable1.getSelectedRow();
        DefaultTableModel model = (DefaultTableModel)jTable1.getModel();
        cat_id = tab_id_cat.get(index);
        if (cat_id == 1) {
            JOptionPane.showMessageDialog(
                this, // Fenêtre parente (null pour aucune)
                "On ne supprime pas la catégorie de base !", // Le message
                "Erreur", // Le titre de la boîte de dialogue
                JOptionPane.ERROR_MESSAGE // Le type de message (icône d'exclamation)
            );
            return;
        }
        int choix = JOptionPane.showConfirmDialog(
            this,
            "Voulez-vous vraiment supprimer la catégorie ?\nLes notes associers seront placées dans la catégorie non classé",
            "Confirmation",
            JOptionPane.YES_NO_OPTION,
            JOptionPane.WARNING_MESSAGE
        );
        if (choix == JOptionPane.YES_OPTION) {
            cat.delete(cat_id);
            fill_cat_list("");
            this.home.refresh_cat();
        }
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // Mise à jour d'une catégorie
        if (cat_id == 1) {
            JOptionPane.showMessageDialog(
                this, // Fenêtre parente (null pour aucune)
                "On ne modifie pas la catégorie de base !", // Le message
                "Erreur", // Le titre de la boîte de dialogue
                JOptionPane.ERROR_MESSAGE // Le type de message (icône d'exclamation)
            );
            return;
        }
        JTextField textField = new JTextField();
        Object[] message = {
            "Nom de la catégorie :", textField
        };

        Object[] options = {"Valider", "Annuler"};

        int choice = JOptionPane.showOptionDialog(
            null,
            message,
            "Saisie",
            JOptionPane.OK_CANCEL_OPTION,
            JOptionPane.PLAIN_MESSAGE,
            null,
            options,
            options[0]
        );

        if (choice == 0) { // Valider
            String valeur = textField.getText();
            if (valeur == null || valeur.trim().isEmpty() || valeur == " ") {
                JOptionPane.showMessageDialog(
                    this,
                    "La catégorie doit avoir un nom valide", // Le message
                    "Erreur", // Le titre de la boîte de dialogue
                    JOptionPane.ERROR_MESSAGE // Le type de message (icône d'exclamation)
                );
                return;
            }
            cat.update(cat_id, valeur);
            fill_cat_list("");
            this.home.refresh_cat();
        }

    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jTextField1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyReleased
        // recherche de catégorie
        String nom_cat = jTextField1.getText();
        fill_cat_list(nom_cat);
    }//GEN-LAST:event_jTextField1KeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        //java.awt.EventQueue.invokeLater(() -> new Category().setVisible(true));
    }
    
    public void fill_cat_list(String nom_cat){
        String[] header = {"nom"};
        String[] note_data = new String[1];
        DefaultTableModel model = new DefaultTableModel(null, header);
        tab_id_cat.clear();
        list = cat.read(nom_cat);
        try {
            for (Map<String, Object> row : list) {
                note_data[0] = row.get("nom").toString();
                model.addRow(note_data);
                tab_id_cat.add((Integer)row.get("id"));
            }
            this.jTable1.setModel(model);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Une erreur s'est produite lors du remplissage de la liste.\n"+e.getMessage());
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
