/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.moon.view;

import com.mycompany.moon.model.CategoryDAO;
import com.mycompany.moon.model.NoteDAO;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import tools.ExportManager;
import tools.TimeConvert;
import javax.swing.ImageIcon;
import java.awt.Image;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;
import tools.DialogMsg;
import tools.ImportManager;
import tools.NotificationManager;

/**
 *
 * @author edithson
 */
public class Home extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Home.class.getName());

    private NoteDAO note = new NoteDAO();
    private ArrayList<String> tab_id_note = new ArrayList<>();
    private ArrayList<String> tab_id_cat = new ArrayList<>();
    private String note_id = "0";
    List<Map<String, Object>> list = null;
    private String search_word = "";
    private String search_cat = "0";
    public static Home instance;
    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
        instance = this;
        CategoryDAO cat = new CategoryDAO();
        System.out.println(">>> Nouvelle instance de Home créée !");
        try {
            List<Map<String, Object>> list_cat = cat.read("");
            jComboBox1.addItem("Toutes les catégories");
            tab_id_cat.add("0");
            for (Map<String, Object> list : list_cat) {
                jComboBox1.addItem(list.get("nom").toString());
                tab_id_cat.add(list.get("id").toString());
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Erreur lors de la selection des catégories...\n"+e.getLocalizedMessage());
        }
        fill_note_list(search_word, search_cat);
        try {
            Image iconImage = new ImageIcon(getClass().getResource("/icons/app_icon.png")).getImage(); 
            this.setIconImage(iconImage);
            System.out.println("Image ok");
        } catch (Exception e) {
            System.err.println("Impossible de charger l'icône de la fenêtre: " + e.getMessage());
        }
        NotificationManager.notify("Moon Note par GZ", "Vos Notes Stellaires");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();

        jMenuItem3.setText("Consulter");
        jMenuItem3.addActionListener(this::jMenuItem3ActionPerformed);
        jPopupMenu1.add(jMenuItem3);

        jMenuItem2.setText("Modifier");
        jMenuItem2.setName("MenuItemModifier"); // NOI18N
        jMenuItem2.addActionListener(this::jMenuItem2ActionPerformed);
        jPopupMenu1.add(jMenuItem2);

        jMenuItem1.setText("Supprimer");
        jMenuItem1.setName("MenuItemSupp"); // NOI18N
        jMenuItem1.addActionListener(this::jMenuItem1ActionPerformed);
        jPopupMenu1.add(jMenuItem1);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("moon note - home");
        setFont(new java.awt.Font("JetBrains Mono Light", 0, 12)); // NOI18N
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("JetBrains Mono NL SemiBold", 0, 24)); // NOI18N
        jLabel1.setText("Moon note");

        jButton1.setFont(new java.awt.Font("JetBrains Mono NL Light", 0, 17)); // NOI18N
        jButton1.setText("Catégorie");
        jButton1.addActionListener(this::jButton1ActionPerformed);

        jButton2.setFont(new java.awt.Font("JetBrains Mono NL Light", 0, 17)); // NOI18N
        jButton2.setText("Nouvelle note");
        jButton2.addActionListener(this::jButton2ActionPerformed);

        jComboBox1.setFont(new java.awt.Font("JetBrains Mono NL Light", 0, 17)); // NOI18N
        jComboBox1.addActionListener(this::jComboBox1ActionPerformed);

        jTextField1.setFont(new java.awt.Font("JetBrains Mono NL Light", 0, 17)); // NOI18N
        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField1KeyReleased(evt);
            }
        });

        jLabel2.setText("Rechercher");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 71, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(2, 2, 2)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTable1.setFont(new java.awt.Font("JetBrains Mono NL Light", 0, 17)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.setComponentPopupMenu(jPopupMenu1);
        jTable1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jTable1.setRowHeight(40);
        jTable1.setRowMargin(5);
        jTable1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jTable1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jTable1.setUpdateSelectionOnSort(false);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jTable1MouseReleased(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jButton3.setFont(new java.awt.Font("JetBrains Mono Light", 0, 17)); // NOI18N
        jButton3.setText("Exporter les notes");
        jButton3.addActionListener(this::jButton3ActionPerformed);

        jButton4.setFont(new java.awt.Font("JetBrains Mono Light", 0, 17)); // NOI18N
        jButton4.setText("Actualiser");
        jButton4.addActionListener(this::jButton4ActionPerformed);

        jButton5.setFont(new java.awt.Font("JetBrains Mono Light", 0, 17)); // NOI18N
        jButton5.setText("Importer des notes");
        jButton5.addActionListener(this::jButton5ActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(135, 135, 135)
                        .addComponent(jButton4)
                        .addGap(18, 18, 18)
                        .addComponent(jButton3)
                        .addGap(18, 18, 18)
                        .addComponent(jButton5)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addComponent(jButton4)
                    .addComponent(jButton5))
                .addContainerGap(36, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(753, 503));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        CreateNote cn = new CreateNote(this);
        cn.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTable1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseReleased
        int index = jTable1.getSelectedRow();
        DefaultTableModel model = (DefaultTableModel)jTable1.getModel();
        //JOptionPane.showConfirmDialog(rootPane, "Note sélectionnée = "+model.getValueAt(index, 1).toString());
        note_id = tab_id_note.get(index);
    }//GEN-LAST:event_jTable1MouseReleased

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // suppression d'une note
        int index = jTable1.getSelectedRow();
        note_id = tab_id_note.get(index);
        int choix = JOptionPane.showConfirmDialog(
            this,
            "Voulez-vous vraiment supprimer la note ?",
            "Confirmation",
            JOptionPane.YES_NO_OPTION,
            JOptionPane.WARNING_MESSAGE
        );
        if (choix == JOptionPane.YES_OPTION) {
            note.delete(note_id);
            fill_note_list(search_word, search_cat);
        }
        
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        //modification d'une note
        int index = jTable1.getSelectedRow();
        note_id = tab_id_note.get(index);
        EditNote editForm = new EditNote(note_id, this);
        editForm.setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // Consultation des notes
        int index = jTable1.getSelectedRow();
        note_id = tab_id_note.get(index);
        ShowNote showForm = new ShowNote(note_id);
        showForm.setVisible(true);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // Ouverture du formulaire des catégorie
        Category catForm = new Category(this);
        catForm.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // recherche lors du changement de catégorie
        
        // Vérifier si l'index est valide (pour éviter Index -1)
        int index = jComboBox1.getSelectedIndex();
        if (index < 0) {
            // La liste a été vidée ou aucun élément n'est sélectionné. On ignore.
            System.out.println("DEBUG: Sélection JComboBox ignorée (index < 0).");
            return;
        }
    
        if (tab_id_cat == null || tab_id_cat.isEmpty()) {
            // La liste n'est pas prête, ignorez l'événement pour l'instant.
            System.out.println("DEBUG: tab_id_cat est vide, recherche ignorée.");
            return; 
        }
        search_cat = tab_id_cat.get(index);
        search_word = jTextField1.getText();
        fill_note_list(search_word, search_cat);
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jTextField1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyReleased
        // recherche lors du changement du mot
        if (tab_id_cat == null || tab_id_cat.isEmpty()) {
            // La liste n'est pas prête, ignorez l'événement pour l'instant.
            System.out.println("DEBUG: tab_id_cat est vide, recherche ignorée.");
            return; 
        }
        int index = jComboBox1.getSelectedIndex();
        search_cat = tab_id_cat.get(index);
        search_word = jTextField1.getText();
        fill_note_list(search_word, search_cat);
        System.out.println("ok");
    }//GEN-LAST:event_jTextField1KeyReleased

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // Exportation des données
        int choix = JOptionPane.showConfirmDialog(
            this,
            "Vous etes sur le point d'exporter toutes vos notes.\nLes notes seront exporter au format JSON dans votre repertoire personnel\n Vous confirmez ?",
            "Confirmation",
            JOptionPane.YES_NO_OPTION,
            JOptionPane.WARNING_MESSAGE
        );
        if (choix == JOptionPane.YES_OPTION) {
            String msg = ExportManager.exportDatabase();
            NotificationManager.notify("Moon Note par GZ", msg);
            JOptionPane.showMessageDialog(this, msg, "Exportation", HEIGHT);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        try {
            note_id = "0";
            search_cat = "0";
            search_word = "";
            jComboBox1.removeAllItems();
            refresh_cat();
            fill_note_list(search_word, search_cat);
            jTextField1.setText("");
            jComboBox1.setSelectedIndex(0);
            DialogMsg.successMsg("Actualisation ok!");
        } catch (Exception e) {
            DialogMsg.errorMsg("Erreur lors de l'actualisation\n"+e.getLocalizedMessage());
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // Action d'importation des notes
        // 1. Créer le JFileChooser
        JFileChooser fileChooser = new JFileChooser();

        // 2. (Optionnel) Définir le répertoire de départ (si vous voulez cibler un dossier spécifique)
        // fileChooser.setCurrentDirectory(new File(System.getProperty("user.home"))); 

        // 3. (Optionnel) Définir un filtre pour n'afficher que certains types de fichiers (ex: images)
        //fileChooser.setFileFilter(new FileNameExtensionFilter("Images (PNG, JPG)", "png", "jpg", "jpeg"));
        fileChooser.setFileFilter(new FileNameExtensionFilter("Fichiers JSON (*.json)", "json"));

        // 4. Afficher la boîte de dialogue "Ouvrir"
        int result = fileChooser.showOpenDialog(this);

        // 5. Gérer le résultat de la sélection
        if (result == JFileChooser.APPROVE_OPTION) {
            // L'utilisateur a cliqué sur "Ouvrir" ou "Sélectionner"

            // Récupérer le fichier sélectionné
            java.io.File selectedFile = fileChooser.getSelectedFile();

            // Afficher le chemin (pour vérification)
            String filePath = selectedFile.getAbsolutePath();
            System.out.println("Fichier sélectionné : " + filePath);

            // 🚀 Lancer l'importation
            String report = ImportManager.importDatabase(filePath);

            // Afficher le rapport
            JOptionPane.showMessageDialog(this, report, "Rapport d'Importation", JOptionPane.INFORMATION_MESSAGE);

        } else if (result == JFileChooser.CANCEL_OPTION) {
            // L'utilisateur a cliqué sur "Annuler" ou fermé la fenêtre
            System.out.println("Sélection annulée par l'utilisateur.");
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        // java.awt.EventQueue.invokeLater(() -> new Home().setVisible(true));
    }
    
    public void fill_note_list(String search_word, String search_cat){
        String[] header = {"Titre", "Catégorie", "Date de création"};
        String[] note_data = new String[3];
        DefaultTableModel model = new DefaultTableModel(null, header);
        this.list = note.read(search_word, search_cat);
        tab_id_note.clear();

        try {
            for (Map<String, Object> row : list) {
                note_data[0] = row.get("titre").toString();
                note_data[1] = row.get("categorie_nom").toString();
                note_data[2] = TimeConvert.formatDateTime(row.get("created_at").toString());
                model.addRow(note_data);
                tab_id_note.add(row.get("id").toString());
            }
            this.jTable1.setModel(model);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Une erreur s'est produite\n"+e.getMessage());
        }
    }
    
    public void refresh_cat(){
        CategoryDAO cat = new CategoryDAO();
        try {
            String nom_cat = "";
            List<Map<String, Object>> list_cat = cat.read(nom_cat);
            jComboBox1.removeAllItems();
            jComboBox1.addItem("Toutes les catégories");
            tab_id_cat.add("0");
            for (Map<String, Object> list : list_cat) {
                jComboBox1.addItem(list.get("nom").toString());
                tab_id_cat.add(list.get("id").toString());
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Erreur lors de la selection des catégories...\n"+e.getLocalizedMessage());
        }
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
